# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"!\n\x0eReverseRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0fReverseResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0eIsPrimeRequest\x12\x0f\n\x07message\x18\x01 \x01(\x03\"\"\n\x0fIsPrimeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\".\n\x0cSplitRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x64\x65lim\x18\x02 \x01(\t\".\n\rSplitResponse\x12\x0e\n\x06length\x18\x01 \x01(\x05\x12\r\n\x05parts\x18\x02 \x03(\t2\x90\x01\n\x06Server\x12,\n\x07reverse\x12\x0f.ReverseRequest\x1a\x10.ReverseResponse\x12&\n\x05split\x12\r.SplitRequest\x1a\x0e.SplitResponse\x12\x30\n\x07isprime\x12\x0f.IsPrimeRequest\x1a\x10.IsPrimeResponse(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REVERSEREQUEST._serialized_start=17
  _REVERSEREQUEST._serialized_end=50
  _REVERSERESPONSE._serialized_start=52
  _REVERSERESPONSE._serialized_end=86
  _ISPRIMEREQUEST._serialized_start=88
  _ISPRIMEREQUEST._serialized_end=121
  _ISPRIMERESPONSE._serialized_start=123
  _ISPRIMERESPONSE._serialized_end=157
  _SPLITREQUEST._serialized_start=159
  _SPLITREQUEST._serialized_end=205
  _SPLITRESPONSE._serialized_start=207
  _SPLITRESPONSE._serialized_end=253
  _SERVER._serialized_start=256
  _SERVER._serialized_end=400
# @@protoc_insertion_point(module_scope)
